/* sessionStorage.setItem('appRouter', './modules/router.js');
sessionStorage.setItem('routerHome', '../home/home.js');
sessionStorage.setItem('homeRouter', '../modules/router.js');
sessionStorage.setItem('hash', '#');
sessionStorage.setItem('hashHome', '#home');
sessionStorage.setItem('hashError', '#error');
sessionStorage.setItem('homePage', '/home/home.html');
sessionStorage.setItem('errorPage', '/error.html');
sessionStorage.setItem('indexContainerId', 'root');
sessionStorage.setItem('loadContentFetchIf', 'home');
sessionStorage.setItem('nav_menu', 'nav_menu');
sessionStorage.setItem('querySelect', 'button[id]');
sessionStorage.setItem('keyBtnNav', 'btnNav');
sessionStorage.setItem('keyBtnHome', 'btn_home');
sessionStorage.setItem('keyBtnError', 'btn_err');

export const getAppRouter = () => sessionStorage.getItem('appRouter');
export const getRouterHome = () => sessionStorage.getItem('routerHome');
export const getHomeRouter = () => sessionStorage.getItem('homeRouter');
export const getHash = () => sessionStorage.getItem('hash');
export const getHashHome = () => sessionStorage.getItem('hashHome');
export const getHashError = () => sessionStorage.getItem('hashError');
export const getHomePage = () => sessionStorage.getItem('homePage');
export const getErrorPage = () => sessionStorage.getItem('errorPage');
export const getIndexContainerId = () => sessionStorage.getItem('indexContainerId');
export const getLoadContentFetchIf = () => sessionStorage.getItem('loadContentFetchIf');
export const getNavMenu = () => sessionStorage.getItem('nav_menu');
export const getQuerySelect = () => sessionStorage.getItem('querySelect');
export const getKeyBtnNav = () => sessionStorage.getItem('keyBtnNav');
export const getKeyBtnHome = () => sessionStorage.getItem('keyBtnHome');
export const getKeyBtnError = () => sessionStorage.getItem('keyBtnError');
 */